version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

networks:
  default:
    driver: bridge

volumes:
  pgdata:
    driver: local
